evaluate:
  type: "shell"
  timeout: 15000
  shell:
    command: 
      - "python"
      - "/app/evaluate.py"
metric:
  type: "shell"
  timeout: 15000
  shell:
    command: 
      - "python"
      - "/app/metric.py"