apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscalerConfig
evaluate:
  type: "shell"
  timeout: 10000
  shell:
    entrypoint: "python"
    command: ["/app/evaluate.py"]
metric:
  type: "shell"
  timeout: 10000
  shell:
    entrypoint: "python"
    command: ["/app/metric.py"]
kubernetesMetricSpecs:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 