dataset_name: alibaba_cluster_trace_v2022
raw_dir: /dataset/raw/alibaba_v2022
parquet_dir: /dataset/parquet/alibaba_v2022
features_dir: /dataset/features/alibaba_v2022

time_col: timestamp
target_col: cpu_utilization
id_cols: [msname, msinstanceid]

freq: 1m

window:
  input_len: 60
  pred_horizon: 5
  stride: 1
